[     UTC     ] Logs for cabotagelens.streamlit.app/ ──────────────────────────────────────────────────────────────────────────────────────── [20:10:54] 🖥 Provisioning machine... [20:10:54] 🎛 Preparing system... [20:10:54] ⛓ Spinning up manager process... [20:10:56] 🚀 Starting up repository: 'carbon-footprint', branch: 'main', main module: 'app/app_streamlit.py' [20:10:56] 🐙 Cloning repository... [20:11:02] 🐙 Cloning into '/mount/src/carbon-footprint'...
[20:11:02] 🐙 Cloned repository!
[20:11:02] 🐙 Pulling code changes from Github...
[20:11:04] 📦 Processing dependencies...

──────────────────────────────────────── uv ───────────────────────────────────────────

Using uv pip install.
Using Python 3.14.3 environment at /home/adminuser/venv
Resolved 42 packages in 560ms
Prepared 42 packages in 2.75s
Installed 42 packages in 120ms
 + altair==6.0.0
 + attrs==26.1.0
 + blinker==1.9.0
 + cachetools==7.0.5
 + certifi==2026.2.25
 + charset-normalizer==3.4.6
 + click==8.3.1
 + currencyconverter==0.18.15
 + et-xmlfile==2.0.0
 + gitdb==4.0.12
 + gitpython==3.1.46
 + [2026-03-23 20:11:07.988007] idna==3.11
 + jinja2==3.1.6
 + jsonschema==4.26.0
 + jsonschema-specifications==[2026-03-23 20:11:07.988208] 2025.9.1
 + markupsafe==3.0.3
 + narwhals==2.18.0
 + numpy==2.4.3
 + openpyxl==3.1.5
 + packaging==26.0
 + pandas==2.3.3
 + pillow==12.1.1
 + protobuf==6.33.6
 + [2026-03-23 20:11:07.988623] psycopg==3.3.3
 + psycopg-binary==3.3.3
 + pyarrow==23.0.1
 + pydeck==0.9.1
 + python-dateutil==2.9.0.post0
 + [2026-03-23 20:11:07.988813] pytz==2026.1.post1
 + referencing==0.37.0
 + requests==2.32.5
 + rpds-py==0.30.0
 + six==1.17.0
 + smmap==5.0.3
 + streamlit[2026-03-23 20:11:07.988965] ==1.55.0
 + tenacity==9.1.4
 + toml==0.10.2
 + tornado==6.5.5
 + typing-extensions==4.15.0
 + tzdata==[2026-03-23 20:11:07.989120] 2025.3
 + urllib3==2.6.3
 + watchdog==6.0.0
Checking if Streamlit is installed
Found Streamlit version 1.55.0 in the environment
Installing rich for an improved exception logging
Using uv pip install.
Using Python 3.14.3 environment at /home/adminuser/venv
Resolved [2026-03-23 20:11:09.936561] 4 packages[2026-03-23 20:11:09.936846]  [2026-03-23 20:11:09.937064] in 141ms[2026-03-23 20:11:09.937273]
Prepared 4 packages in 166ms
Installed 4 packages in 18ms
 + markdown-it-py[2026-03-23 20:11:10.124719] ==4.0.0
 + mdurl==0.1.2
 + pygments==2.19.2
 + rich==14.3.3

────────────────────────────────────────────────────────────────────────────────────────

[20:11:10] 🐍 Python dependencies were installed from /mount/src/carbon-footprint/requirements.txt using uv.
[20:11:10] 📦 WARN: More than one requirements file detected in the repository. Available options: uv /mount/src/carbon-footprint/requirements.txt, poetry /mount/src/carbon-footprint/pyproject.toml. Used: uv with /mount/src/carbon-footprint/requirements.txt
Check if streamlit is installed
Streamlit is already installed
[20:11:11] 📦 Processed dependencies!

────────────────────── Traceback (most recent call last) ───────────────────────
  /home/adminuser/venv/lib/python3.14/site-packages/streamlit/runtime/scriptru
  nner/exec_code.py:129 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.14/site-packages/streamlit/runtime/scriptru
  nner/script_runner.py:689 in code_to_exec

  /mount/src/carbon-footprint/app/app_streamlit.py:11 in <module>

     8
     9 import streamlit as st
    10
  ❱ 11 from app.access import require_app_access
    12 from app.heatmap.config import HEATMAP_PAGE_ICON
    13 from app.main.styles import inject_css
    14 from app.main.utils.constants import APP_NAME, PAGE_ICON, PAGE_LAYOUT
────────────────────────────────────────────────────────────────────────────────
ModuleNotFoundError: No module named 'app'